# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 858a676c46689c20abb34b8e67e37179295e081aa646b1d54455020bef1fdd156f1bef3849de3b220a605a77c4a7fe2102c929c07bf7ecd329188205e0e5902d

test:
  secret_key_base: c7d001bd9ed6600b3a1a805445d7643df1c8be7424b541150c44680bd9a01d6c9baefcf7a0ba5e63e106e062d24a23516f95064a3233a876cc369d5e23b60928

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
